'use strict';

var messages = {
  nl: {
    noWebSocketSupport: 'Deze browser ondersteunt geen WebSocket.',
    chooseTrumpHeading:  'Kies je troef',
    chooseTrump:  'Klik 1 van je kaarten aan om de troef te kiezen.',
    yourTurn:  'Jij bent aan de beurt...',
    youWinHand:  'Jij hebt deze hand gemaakt!',
    otherWinsHand: '\nheeft deze hand gemaakt!',
    errorMessage:  'Ai ai ai!\nEr is een fout opgetreden.',
    invalidMoveHeading:  'Ongeldige kaart!',
    invalidMove:  'Kies een andere kaart om verder\nte spelen',
    playerPrefix:  'Anoniem',
    score:  'Stand',
    clickToAdvance:  'Klik om door te gaan...',
    clickToStart:  'Klik om te beginnen...',
    gameDecided: "Spel afgelopen!.\n Winaar is ",
    gameTitle:  'TroefCall Online'
  }
};

var names = {
MALE_NL: [
    'Lucas',
    'Daan',
    'Sem',
    'Milan',
    'Thomas',
    'Luuk',
    'Lars',
    'Levi',
    'Bram',
    'Finn',
    'Thijs',
    'Jayden',
    'Ruben',
    'Tim',
    'Stijn',
    'Julian',
    'Jesse',
    'Mees',
    'Noah',
    'Luca',
    'Willem',
    'Henk',
    'Jan',
    'Peter',
    'Martijn',
    'Christiaan'
],
MALE_SU : [
    'Harold',
    'Ronald',
    'Damian',
    'Rajesh',
    'Rakesh',
    'Suresh',
    'Dinesh',
    'Ritesh',
    'Prem',
    'Mahinder',
    'Sammy',
    'Desi',
    'Jurgen',
    'Vinod',
    'Abdoel',
    'Marciono',
    'Luciano',
    'Sylvano',
    'Quincy',
    'Regilio',
    'Giuliano'
],
FEMALE_NL : [
    'Emma',
    'Julia',
    'Sophie',
    'Anna',
    'Lynn',
    'Isa',
    'Lotte',
    'Fleur',
    'Lisa',
    'Sara',
    'Lieke',
    'Eva',
    'Saar',
    'Tess',
    'Anne',
    'Femke',
    'Evi',
    'Sarah',
    'Sanne'
],
FEMALE_SU : [
    'Glenda',
    'Yvonne',
    'Marijke',
    'Reshma',
    'Shirley',
    'Shayenne',
    'Lila'
]
};
